# Generated by Django 4.0.5 on 2022-06-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(max_length=64),
        ),
    ]
